language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

rvm:
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

env:
  - BUNDLE_FORCE_RUBY_PLATFORM=1

before_install:
  - gem update --system
  - gem install bundler
